MvcCoreClientesWCF/Models/ErrorViewModel.cs
using System;

namespace MvcCoreClientesWCF.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreClientesWCF/Models/Provincia.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreClientesWCF.Models
{
    public class Provincia
    {
        public int IdProvincia { get; set; }
        public string Nombre { get; set; }
    }
}

MvcCoreClientesWCF/Controllers/CatastroController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreClientesWCF.Models;
using MvcCoreClientesWCF.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreClientesWCF.Controllers
{
    public class CatastroController : Controller
    {
        private ServiceCatastro service;

        public CatastroController(ServiceCatastro service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            List<Provincia> provincias = await this.service.GetProvincias();
            return View(provincias);
        }

        public async Task<IActionResult> Municipios(string provincia)
        {
            List<string> municipios = await this.service.GetMuniciops(provincia);
            return View(municipios);
        }
    }
}

MvcCoreClientesWCF/Controllers/CochesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreClientesWCF.Services;
using ReferenceCoches;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreClientesWCF.Controllers
{
    public class CochesController : Controller
    {
        private ServiceCoches service;

        public CochesController(ServiceCoches service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            Coche[] coches = await this.service.GetCocheAsync();
            return View(coches);
        }

        public async Task<IActionResult> Details(int idcoche)
        {
            Coche coche = await this.service.FindCocheAsync(idcoche);
            return View(coche);
        }
    }
}

MvcCoreClientesWCF/Controllers/CountriesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreClientesWCF.Services;
using ServicioCountries;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreClientesWCF.Controllers
{
    public class CountriesController : Controller
    {
        private ServicesCountries services;

        public CountriesController(ServicesCountries services)
        {
            this.services = services;
        }

        public async Task<IActionResult> Index()
        {
            tCountryCodeAndName[] countries = await this.services.GetCountries();
            return View(countries);
        }

        public async Task<IActionResult> Detalles(string iso)
        {
            tCountryInfo country = await this.services.InformacionPais(iso);
            return View(country);
        }
    }
}

MvcCoreClientesWCF/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcCoreClientesWCF.Models;
using MvcCoreClientesWCF.Services;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreClientesWCF.Controllers
{
    public class HomeController : Controller
    {
        private ServiceVariosMetodos service;

        public HomeController(ServiceVariosMetodos service)
        {
            this.service = service;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(int numero)
        {
            int[] results = await this.service.GetTablaMultiplicar(numero);
            return View(results);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreClientesWCF/Controllers/NumberToWordsController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreClientesWCF.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreClientesWCF.Controllers
{
    public class NumberToWordsController : Controller
    {
        private ServiceNumberConversion service;

        public NumberToWordsController(ServiceNumberConversion service)
        {
            this.service = service;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(int numero)
        {
            string response = await this.service.GetNumberToWords(numero);
            ViewData["RESPONSE"] = response;
            return View();
        }
    }
}

MvcCoreClientesWCF/Views/Catastro/Index.cshtml
@model List<Provincia>

<h1>Provincias</h1>
<ul>
    @foreach (Provincia provincia in Model)
    {
        <li>
            @provincia.Nombre 
            &nbsp;
            <a asp-controller="Catastro" asp-action="Municipios" asp-route-provincia="@provincia.Nombre" class="btn btn-outline-primary">Municipios</a>
        </li>
    }

</ul>

MvcCoreClientesWCF/Views/Catastro/Municipios.cshtml
@model List<string>

<h1>Municipios</h1>
<ul>
    @foreach (string str in Model)
    {
        <li>
            @str
          
        </li>
    }

</ul>

MvcCoreClientesWCF/Views/Coches/Details.cshtml
@model Coche

<a asp-action="Index" asp-controller="Coches">Volver</a>

<ul class="list-group">
    <li class="list-group-item list-group-item-warning">
        Marca: @Model.Marca
    </li>
    <li class="list-group-item list-group-item-warning">
        Modelo: @Model.Modelo
    </li>
    <li class="list-group-item list-group-item-warning">
        Imagen: <img src="@Model.Imagen" style="max-height:100px; max-width:100px;"/>
    </li>
</ul>

MvcCoreClientesWCF/Views/Coches/Index.cshtml
@model Coche[]

    <h1 style="color: darkblue">COCHES WCF</h1>

    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Marca</td>
                <td>Modelo</td>
                <td>Imagen</td>
            </tr>
        </thead>
        <tbody>
            @foreach (Coche coche in Model)
            {
            <tr>
                <td>@coche.Marca</td>
                <td>@coche.Modelo</td>
                <td>
                    <img src="@coche.Imagen" style="max-height: 100px; max-width: 100px;"/>
                </td>
                <td>
                    <a asp-controller="Coches" asp-action="Details" asp-route-idcoche="@coche.IdCoche" class="btn btn-outline-secondary">
                        Ver detalles
                    </a>
                </td>
            </tr>
            }

        </tbody>
    </table>

MvcCoreClientesWCF/Views/Countries/Detalles.cshtml
@model tCountryInfo

<ul>
    <li>ISO CODE: @Model.sISOCode</li>
    <li>Nombre: @Model.sName</li>
    <li>Capital: @Model.sCapitalCity</li>
    <li>Codigo telefono: @Model.sPhoneCode</li>
    <li>Currency ISO: @Model.sCurrencyISOCode</li>
    <li>Bandera: @Model.sCountryFlag</li>
    <li>Lenguas: @Model.Languages</li>
</ul>

MvcCoreClientesWCF/Views/Countries/Index.cshtml
@model tCountryCodeAndName[]


<table>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Detalles</th>
        </tr>
    </thead>
    <tbody>
        @foreach (tCountryCodeAndName country in Model)
        {
        <tr>
            <td>@country.sName</td>
            <td>@country.sISOCode</td>
            <td>
                <a class="btn btn-outline-info" asp-controller="Countries" asp-action="Detalles" asp-route-iso="@country.sISOCode">
                    Ver detalles
                </a>
            </td>
        </tr>
        }
        </tbody>
</table>

MvcCoreClientesWCF/Views/Home/Index.cshtml
@model int[]

<div class="text-center">
    <form method="post">
        <label>Numero para ver su tabla de multiplicar</label>
        <input type="number" name="numero" class="form-control" />
        <br />
        <button class="btn btn-info" type="submit">
            Enviar
        </button>
    </form>
</div>

@if(Model != null)
            {
                <hr />
                <ul class="list-group">
                    @foreach (int num in Model)
                    {
                        <li class="list-group-item">
                            @num
                        </li>
                    }
                </ul>
                
            }

MvcCoreClientesWCF/Views/NumberToWords/Index.cshtml
@model string
@{
    ViewData["Title"] = "Index";
}


<form method="post">
    <label>Número: </label>
    <input type="text" name="numero" class="form-control"/>
    <button type="submit" class="btn btn-outline-danger">
        LLamar al servicio
    </button>
</form>
<br />
<h1 style="color:darkcyan">@ViewData["RESPONSE"]</h1>

MvcCoreClientesWCF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreClientesWCF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreClientesWCF</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="Index">Countries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NumberToWords" asp-action="Index">Palabras</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catastro" asp-action="Index">Provincias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Coches" asp-action="Index">Coches</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcCoreClientesWCF - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>